var CHAR_ACTION = {
    IDLE: 0,
    WALK_DOWN: 1,
    WALK_LEFT: 2,
    WALK_RIGHT: 3,
    WALK_UP: 4,
}

var CHAR_ACTION_NUM_SPRITES = {
    IDLE_MIN: 0,
    IDLE_MAX: 0,
    WALK_DOWN_MIN: 1,
    WALK_DOWN_MAX: 4,
    WALK_RIGHT_MIN: 11,
    WALK_RIGHT_MAX: 14,
    WALK_UP_MIN: 23,
    WALK_UP_MAX: 26,
    WALK_LEFT_MIN: 33,
    WALK_LEFT_MAX: 36,

}

CHAR_FRAME_RATE = 6;

FRAME_RATE = 30;